apiVersion: v1
kind: Service
metadata:
  name: eminsights-backend
spec:
  type: NodePort
  selector:
    app: eminsights-backend
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30007
